name: Run Infection

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  LIBRDKAFKA_VERSION: v1.4.2

jobs:
  Infection:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose -f tests/docker-compose.yaml up -d

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: Install PHP
        uses: shivammathur/setup-php@2.2.0
        with:
          php-version: 7.3
          coverage: pcov
          tools: pecl
          extensions: json, mbstring, rdkafka

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Infection
        run: vendor/bin/infection --min-msi=40 --min-covered-msi=50 --log-verbosity=none -s
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
